Card component
j24m/Flame-UI pull request #4
Opened 2022-02-08 09:24 UTC by j24m

Card components completed.

2022-02-08 09:39 UTC, samyakshah3008 approved these changes
Good job, Jyotsna. 
Looks good to merge!

2022-02-08 09:58 UTC, zoef-yt requested changes
Give consistent spacing between blocks of codes. use relative units like rem in place of px.

2022-02-08 09:58 UTC, zoef-yt commented on Components/card.css
> + /* height:500px; */
remove commented code.

2022-02-08 09:58 UTC, zoef-yt commented on Components/card.css
> +    /* aspect-ratio: 4/3; */
remove commented code.

2022-02-08 09:58 UTC, zoef-yt commented on Components/card.css
> +  /* border:10px solid black ; */
remove commented code.

2022-02-08 09:58 UTC, zoef-yt commented on Components/card.css
> +    /* aspect-ratio: 1/1; */
remove commented code.

2022-02-08 09:58 UTC, zoef-yt commented on Components/card.css
> +    /* border:solid black; */
remove commented code.

2022-02-08 09:58 UTC, zoef-yt commented on Components/card.css
> +    /* height: 55vh; */
remove commented code.

2022-02-08 09:58 UTC, zoef-yt commented on Components/card.css
> +    background-color: rgba(255, 255, 255, 0.5);
use var for colour

2022-02-08 09:58 UTC, zoef-yt commented on Components/card.css
> +    font-size:30px;
use rem

2022-02-08 09:58 UTC, zoef-yt commented on Components/card.css
> +    /* border:solid red; */
remove commented code.

2022-02-08 09:58 UTC, zoef-yt commented on Components/card.css
> +    font-size: 12px;
use rem

2022-02-08 09:59 UTC, rahulk31 commented on Components/card.css
>  }
Commented Comments can be removed.

2022-02-08 10:00 UTC, rahulk31 commented on Components/card.css
> +
Here and few more places: Commented comments can be removed.

2022-02-08 10:02 UTC, rahulk31 reviewed
Plan to use relative values, other than looks good to me overall. Good to merge.

2022-02-08 10:05 UTC, rahulyadav139 approved these changes

2022-02-08 10:05 UTC, rahulyadav139 commented on Components/card.css
> +    background-color: var(--card-boxshadow-color);
colour variable names are simple and readable. But use rem instead of px. Other than that great work.

2022-02-08 10:17 UTC, merged

2022-02-08 10:32 UTC, saurabhchirde commented on Components/card.css
> +.catwoman-powerpuffgirls-img{
giving a specific class name can be avoided, as it will be difficult to use it in other cards.

2022-02-08 10:32 UTC, saurabhchirde commented on Components/card.css
> +}
Try to create a common heading class and use it on all cards for consistent font size and spacing.

2022-02-08 10:32 UTC, saurabhchirde commented on Components/card.css
> +}
Here as well, you have created a specific class for the keyboard. What, if someone wants to add a mobile phone or any other product.

2022-02-08 10:32 UTC, saurabhchirde commented on Components/card.html
> +        </div>
I loved the color combination and cleaned layout. Class naming is also good, anyone can easily go through it. 
After implementing above mentioned changes, you are good to merge. On e-commerce overlay card, you can improve the text visibility.
<img width="497" alt="Screenshot 2022-02-08 at 3 59 59 PM" src="https://user-images.githubusercontent.com/92800463/152969641-ff8333e1-1116-4033-9d90-4a320f4b2caf.png">

2022-02-21 13:06 UTC, j24m commented on Components/card.html
> +        </div>
Thankyou so much for the suggestions.